### ISSUE TITLE
FATAL EXCEPTION on launch

### ISSUE THREAD

**Issue by twolfturner** [andresantoniocastro/weather#1]
@andresantoniocastro 

```
06-12 23:44:31.546 8502-8502/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.castro.andres.cnntakehome, PID: 8502
                                                 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: org.json.JSONException: No value for deg
                                                     at org.json.JSONObject.get(JSONObject.java:392)
                                                     at org.json.JSONObject.getDouble(JSONObject.java:447)
                                                     at com.castro.andres.cnntakehome.data.parser.QueryResponseToWeatherParser$Companion.parseCurrentJson(QueryResponseToWeatherParser.kt:29)
                                                     at com.castro.andres.cnntakehome.network.RESTAsyncTask.onPostExecute(RESTAsyncTask.kt:57)
                                                     at com.castro.andres.cnntakehome.network.RESTAsyncTask.onPostExecute(RESTAsyncTask.kt:10)
                                                     at android.os.AsyncTask.finish(AsyncTask.java:695)
                                                     at android.os.AsyncTask.-wrap1(Unknown Source:0)
                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

```

<img width="334" alt="screen shot 2018-06-12 at 7 45 32 pm" src="https://user-images.githubusercontent.com/30933499/41322865-5423d20c-6e79-11e8-9853-514a7f8d5b19.png">

**Comment by andresantoniocastro** [comment]
Issue is mitigated in 88f858371485a7ab5f58f9761d4551f7be18fd67 . 

Since we can't guarantee messages being received perfectly every time; anytime a field is missing do the best we can to alert the user that some data is missing ("n/a" or "unknown") until next server request. If something really goes wrong (malformed JSON) we mark the entry an error so its not mistakenly tried to be shown to the user.
